{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000229AA384980>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))"},"timestamp":"2025-08-06 09:24:56,545+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC03E00>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:24:56,549+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C2F0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:06,556+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2CDD0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:06,560+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2D670>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:16,568+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC039E0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:16,576+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA360290>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:26,589+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA745C40>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:26,596+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C560>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:36,614+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2DAF0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:36,622+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA398080>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:46,631+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC02FC0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:46,640+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC031A0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:56,648+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2DA30>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:25:56,654+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C9B0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:06,659+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC03560>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:06,666+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC032F0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:16,670+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA40A6F0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:16,675+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C9B0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:26,684+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2D9A0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:26,692+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2E450>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:36,706+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA36D0A0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:36,712+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC036E0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:46,728+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC035F0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:46,735+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C590>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:56,742+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2E300>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:26:56,747+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC02C90>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:06,760+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229A9C1AB40>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:06,772+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA30C380>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:16,778+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C410>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:16,780+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2D820>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:26,787+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA349310>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:26,800+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA3CA090>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:36,804+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC034D0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:36,811+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC03320>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:46,813+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2CBF0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:46,813+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC03FE0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:56,822+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC02D80>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:27:56,822+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA3327E0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:06,835+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA34B0B0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:06,844+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C680>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:16,848+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2D100>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:16,848+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA30C560>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:26,859+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA36D7C0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:26,859+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC02F90>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:36,874+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2D8E0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:36,874+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2D970>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:46,884+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA39B6B0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:46,896+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA34B380>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:56,899+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC02CF0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:28:56,899+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC02FC0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:06,916+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C980>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:06,916+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC03C50>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:16,927+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC039E0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:16,935+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA3491C0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:26,940+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA36C2F0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:26,940+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C410>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:36,963+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2E690>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:36,967+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA30C560>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:46,976+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA349220>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:46,976+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC02CF0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:56,982+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2D460>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:29:56,982+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2D6A0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:06,993+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC03EF0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:07,003+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA34A6C0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:17,005+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA363E30>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:17,005+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA384980>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:27,015+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C590>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:27,022+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA384AA0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:37,031+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA3608C0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:37,031+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA416810>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:47,037+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC038C0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:47,037+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2D700>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:57,047+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2EED0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:30:57,055+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC02CF0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:34:23,967+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA349CD0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:34:23,984+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA30C560>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:34:33,996+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C590>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:34:34,003+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2EC30>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:34:44,010+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA36EA20>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:34:44,012+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA348200>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:34:54,019+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC02E10>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:34:54,028+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC03A70>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:04,042+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2EC00>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:04,050+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC03230>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:14,075+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC03470>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:14,079+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA348830>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:24,086+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA36D760>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:24,087+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C170>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:34,100+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229A9C1AB40>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:34,100+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA747890>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:44,113+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC03EF0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:44,118+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA3491C0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:54,129+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2C170>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:35:54,129+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC2DB20>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:36:04,228+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC02E40>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:36:04,234+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA77FA70>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:36:14,244+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA30C560>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:36:14,244+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA30C5C0>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:36:24,261+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA747890>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:36:24,261+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3ALUPIN-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AAC03E30>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:36:45,921+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/history?symbol=NSE%3AGLAND-EQ&resolution=5&date_format=1&range_from=2025-08-05&range_to=2025-08-06&cont_flag=1 (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000229AA349B20>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))"},"timestamp":"2025-08-06 09:36:57,598+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-08-07 09:20:21,266+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-08-07 09:20:21,783+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-08-07 09:20:32,398+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-08-07 09:20:32,863+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-08-07 09:20:43,350+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":-16,"message":"Could not authenticate the user","s":"error"}},"timestamp":"2025-08-07 09:20:43,984+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":429,"message":"request limit reached","s":"error"}},"timestamp":"2025-08-18 19:54:04,967+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":429,"message":"request limit reached","s":"error"}},"timestamp":"2025-08-18 19:54:04,975+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":429,"message":"request limit reached","s":"error"}},"timestamp":"2025-08-18 19:54:04,981+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":429,"message":"request limit reached","s":"error"}},"timestamp":"2025-08-18 19:54:05,011+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":429,"message":"request limit reached","s":"error"}},"timestamp":"2025-08-18 19:54:05,138+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":429,"message":"request limit reached","s":"error"}},"timestamp":"2025-08-18 19:54:05,148+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":429,"message":"request limit reached","s":"error"}},"timestamp":"2025-08-18 19:54:06,122+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":429,"message":"request limit reached","s":"error"}},"timestamp":"2025-08-18 19:54:06,403+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:146] fyersModel","message":{"API":"/history","Error":{"code":429,"message":"request limit reached","s":"error"}},"timestamp":"2025-08-18 19:54:09,884+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"},"timestamp":"2025-08-21 11:50:30,509+0530","service":"FyersAPI"}
{"level":"ERROR","location":"[get_call:164] fyersModel","message":{"API":"/history","error":"('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"},"timestamp":"2025-08-21 16:44:29,532+0530","service":"FyersAPI"}
